export const LEGAL_CONTENT = {
  privacy: {
    title: "Privacy Policy",
    content: `
# Privacy Policy

Last Updated: March 16, 2026

At Accurate BMI Calculator, we take your privacy seriously. This policy outlines how we handle your data.

## 1. Data Collection
We do not store any personal health data on our servers. All calculations (height, weight, age, gender) are performed locally in your browser. We do not collect names, addresses, or sensitive medical history.

## 2. Cookies
We use essential cookies to ensure the website functions correctly. We may use third-party analytics (like Google Analytics) to understand how users interact with our site, which helps us improve our content.

## 3. Third-Party Links
Our site may contain links to external websites. We are not responsible for the privacy practices or content of these third-party sites.

## 4. Security
We use industry-standard SSL encryption to protect your connection to our website.

## 5. Contact Us
If you have any questions about this Privacy Policy, please contact us at support@probmi.com.
`
  },
  terms: {
    title: "Terms of Service",
    content: `
# Terms of Service

Last Updated: March 16, 2026

By using Accurate BMI Calculator, you agree to the following terms:

## 1. Use of the Site
The content on this site is for personal, non-commercial use only. You may not use this site for any illegal or unauthorized purpose.

## 2. No Medical Advice
The calculations and information provided are for educational purposes only. They are not a substitute for professional medical advice, diagnosis, or treatment.

## 3. Accuracy of Information
While we strive for accuracy, we do not guarantee that the results provided by the calculator are 100% accurate for every individual. Health metrics can vary based on many factors not captured by BMI.

## 4. Limitation of Liability
Accurate BMI Calculator and its creators are not liable for any damages arising from the use or inability to use the site or the information provided herein.

## 5. Changes to Terms
We reserve the right to modify these terms at any time. Your continued use of the site signifies your acceptance of any changes.
`
  },
  cookies: {
    title: "Cookie Policy",
    content: `
# Cookie Policy

Last Updated: March 16, 2026

This site uses cookies to improve your experience.

## What are Cookies?
Cookies are small text files stored on your device when you visit a website.

## How we use them:
- **Essential Cookies:** Necessary for the site to function.
- **Analytics Cookies:** Help us understand how many people visit our site and which pages are most popular.

## Managing Cookies
You can choose to disable cookies through your browser settings, but some parts of the site may not function correctly as a result.
`
  },
  disclaimer: {
    title: "Medical Disclaimer",
    content: `
# Medical Disclaimer

**IMPORTANT: READ CAREFULLY**

The Accurate BMI Calculator is designed to provide a general estimate of body mass index based on user-provided height and weight.

## 1. Not Medical Advice
The results generated by this tool are NOT medical advice. They should not be used to diagnose or treat any health condition.

## 2. Consult a Professional
Always consult with a licensed physician or healthcare professional before making significant changes to your diet, exercise routine, or health management. BMI is a limited metric and does not account for muscle mass, bone density, or overall body composition.

## 3. No Doctor-Patient Relationship
Use of this website does not create a doctor-patient relationship between you and Accurate BMI Calculator.

## 4. Accuracy
Health calculations are based on standard formulas (Quetelet Index). Individual results may vary.
`
  }
};
